def romNumbers(r):
    match r:
        case "I":
            return 1
        case "I":
            return 1
        case "I":
            return 1
        case "I":
            return 1
        case "I":
            return 1    